import sendMail from "../utils/mailBuilder";

export const registerMailService = (name:string, activationCode: string, email:string) => {
    const html = `<!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>LMS Activation Email</title><style type="text/css">body{margin: 0;padding: 0; min-width: 100%;font-family: Arial, Helvetica, sans-serif;font-size: 16px;line-height: 1.5;background-color: #fafafa;color: #222222;}a{color: #000;text-decoration: none;}h1{font-size: 24px;font-weight: 700;line-height: 1.25;margin-top: 0;margin-bottom: 15px;text-align: center;}p{margin-top: 0;margin-bottom: 24px;}table td{vertical-align: top;}.email-wrapper{max-width: 600px;margin: 0 auto;}.email-header{background-color: #0070f3; padding: 24px;color: #ffffff;}.email-body{padding: 24px;background-color: #ffffff;}.email-footer{background-color: #f6f6f6;padding: 24px;}</style></head><body><div class="email-wrapper"><div class="email-header"><h1>Wellcome to LMS</h1></div><div class="email-body"><p>Hello ${name}</p><p>Thank you for registering with LMS. To activate youe account, please use the following activation code:</p><h2>${activationCode}</h2><p>Please enter this code on the activation page within the next 5 minutes.</p><p>If you did not register for a BaLT account, please ignore this email.</p></div><div class="email-footer"><p>If you have any questions, please don't hesitate to contact us at <a href="mailto:khailendraprasad@gmail.com"> khailendraprasad@gmail.com</a></p></div></div></body></html>`
    const subject = "Activate your account";
    sendMail(email, subject, html);
}

interface INotificationMailServiceData{
    name: string;
    title: string;
}
export const notificationMailService = (data: INotificationMailServiceData, email:string) => {
    const html = `<!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>New Reply Notification on LMS</title><style>body {font-family: Arial, sans-serif; margin: 0;padding: 0;background-color: #f4f4f4;}.container {width: 100%;max-width: 600px;margin: 0 auto; background-color: #ffffff;box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);border-radius: 8px;overflow: hidden;}.content {padding: 20px;}.content h1 {color: #333333;}.content p {line-height: 1.6;color: #666666;}.footer {text-align: center; padding: 10px; background-color: #f1f1f1; color: #999999;font-size: 12px;}</style></head><body><div class="container"><div class="content"><h1>Hello ${data.name},</h1><p>A new reply has been added to your question in the video "<strong>${data.title}</strong>".</p><p>Please login to our website to view the reply and continue the discussion.</p><p>Thank you for being a part of our community!</p></div><div class="footer">&copy; ${new Date().getFullYear()} Your LMS. All rights reserved.</div></div></body></html>`
    const subject = "Question Reply";
    sendMail(email, subject, html);
}

export const orderConfirmationMailService = (order:any, email:string) =>{
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet"><title>Order Confirmation</title><style>body{font-family:"Poppins",sans-serif;margin:0;padding:0;background-color:#f9fafc;color:#333}.container{max-width:700px;margin:40px auto;padding:20px;background-color:#ffffff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}.header{text-align:center;padding-bottom:20px;border-bottom:2px solid #f0f0f0}.header h1{font-size:24px;color:#4f5ef1;margin:0}.header p{font-size:16px;color:#666;margin:5px 0 0}.order-details{padding:20px 0;border-bottom:2px solid #f0f0f0}.order-details h2{font-size:20px;color:#333;margin-bottom:20px}.order-info,.items-table{width:100%;margin-bottom:20px}.order-info th,.order-info td,.items-table th,.items-table td{text-align:left;padding:10px;border:1px solid #e0e0e0}.items-table th{background-color:#f0f0f0}.total{text-align:right;font-size:18px;font-weight:600;margin-top:10px}.footer{text-align:center;padding-top:20px}.footer p{font-size:14px;color:#777}.footer a{color:#4f5ef1;text-decoration:none}</style></head><body><div class="container"><div class="header"><h1>Order Confirmation</h1><p>Your LMS order is confirmed! We're just as excited as you are.</p></div><div class="order-details"><h2>Order Details</h2><table class="order-info"><tr><th>Order #</th><td>${order._id}</td></tr><tr><th>Order Date</th><td>${order.date}</td></tr></table><table class="items-table"><tr><th>Item</th><th>Qty</th><th>Cost</th></tr><tr><td>${order.name}</td><td>1</td><td>${order.price}</td></tr></table><div class="total"><p>Subtotal: $${order.price}</p><p>Total: $${order.price}</p></div></div><div class="footer"><p>If you have any questions, please contact our support team at <a href="mailto:khailendraprasad@gmail.com">khailendraprasad@gmail.com</a></p><p>&copy; 2024 Your LMS. All rights reserved.</p></div></div></body></html>`
    const subject = "Order Confirmation";
    sendMail(email, subject, html);
}